### PR TITLE
feat (events): allow to hide all day events

### PR DESCRIPTION
**Pull request by jgoldhammer**
### Status
**READY**

### Description
- previously all type of events are displayed
- now the user is able to hide all-day events completely
- now the user is able to show only all-day events with a contained meeting link

### CODE REVIEW

**Comment by jgoldhammer** [comment]
@leits - it is possible to review and merge it?

**Comment by leits** [comment]
I'm careful not to overload the settings.
I'm thinking of separating the "Events to hide" option. What do you think?

**Comment by leits** [comment]
@jgoldhammer ^ please, take a look.

**Comment by jgoldhammer** [comment]
I would say we should close this pull request. I have made several improvements over the last days in the same branch, so I don´t know if you will ever merge all my changes back. My intention was to learn Swift and improve a cool existing project. So I did not want to wait until my first changes are merged. What do you think?

**Pull request merged**
