### PR TITLE
Allows hiding past events

### PR DESCRIPTION
**Pull request by dev10110**
### Status
READY

### Description
Allows hiding events in the past, instead of just adding a checkmark to the side of the event. 
Exposes an user-option to set this field, defaults to false to maintain past behaviour.

### CODE REVIEW

**Review by Itaybre — COMMENTED** [review]
The file `MeetingBar/MeetingBar.xcodeproj/project.xcworkspace/xcuserdata/devanshagrawal.xcuserdatad/UserInterfaceState.xcuserstate` should be ignore and not pushed

**Comment by dev10110** [comment]
@Itaybre ah that seems to have slipped through indeed. I'll close this pr and open a new one. Thanks!

**Comment by dev10110** [comment]
oh, I realised I could just git rm the file. I believe it should be gone now. I've also removed the gitignore file I temporarily added. I hope this doesnt screw with the history too much!

**Comment by leits** [comment]
@dev10110 
What do you think about combining this option with disablePastEvents?

**Comment by dev10110** [comment]
I don't mind! So some sort of drop down where you select either hide, cross out or allow joining?

**Comment by leits** [comment]
I think this feature has been on the review for too long. I'll think about improving UX separately.
Thanks, @dev10110 !

**Review by leits — APPROVED** [review]

**Comment by dev10110** [comment]
my apologies for the delay :)

**Pull request merged**
