### PR TITLE
Fix/181 incorrect time statusbar

### PR DESCRIPTION
**Pull request by jgoldhammer**
### Status
**READY**

### Description
Replaced NSBackgroundActivityScheduler with Timer implementation and placed the timer in the current runloop to also trigger the updates when the app is not in focus of the user

More details here:
https://www.hackingwithswift.com/articles/117/the-ultimate-guide-to-timer

### Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

### CODE REVIEW

**Comment by leits** [comment]
Such a great and simple! Thanks!
I'll merge and run it locally for myself to test the changes.

**Review by leits — APPROVED** [review]

**Comment by jgoldhammer** [comment]
@leits - thanks. Hopefully it will fix these problems.

**Comment by 2Grey** [comment]
@jgoldhammer, are you sure, that you should use 
```swift
let timer = Timer.scheduledTimer(timeInterval: 15, target: self, selector: #selector(updateStatusbar), userInfo: nil, repeats: true)
RunLoop.current.add(timer, forMode: .common)
```

Because when you init timer with `scheduledTimer` it add it to current RunLoop:
Description from Apple Doc:
> Creates a timer and schedules it on the current run loop in the default mode.

I think you should create it like this (without `scheduledTimer`):
```swift
let timer = Timer(timeInterval: 15.0, target: self, selector: #selector(updateStatusbar), userInfo: nil, repeats: true)
RunLoop.current.add(timer, forMode: .common)
```

**Comment by jgoldhammer** [comment]
Great catch @2Grey ! I will create a PR for this ...

**Pull request merged**
