### PR TITLE
Add "Run Apple Script on keyboard shortcut" feature

### LINKED ISSUE #573: Feature: Run AppleScript on keyboard shortcut
### Issue that this suggestion fixes

When I'm working from my office I need to dig into a meeting's notes to find the Zoom meeting id and passcode so I can join from a conference room. I've written up a nice AppleScript that finds these from the meeting notes and displays a dialog with them (can share if interested) **but** instead of running this script on every meeting, I want to run it "on-demand" when I decide to go into a conference room.

### Solution description

An extra row in the "Advanced" section of the app preferences:

`Run AppleScript when you press <keyboard shortcut>            <Edit script>`

### Alternatives considered

I thought about writing my own app to do this but so many of the moving parts are already here!

### Additional context

I'm an iOS developer, already poked around in the code and it looks like this will be pretty easy to add. I am **more** than happy to do so myself in the next few days, I just wanted to get a 👍 from you that its a feature you'd be interested in supporting?

### PR DESCRIPTION
**Pull request by neilkimmett**
### Status
**READY**

### Description
Closes #573.
Adds support to run an AppleScript when you press a keyboard shortcut.

image

- Wasn't sure whether to add a "test" button in there too?.
- Also not sure how localization works.
- Missed the CHANGELOG entry, let me add that now

## Checklist
- [ ] Localized
- [x] Added to changelog:
  - [x] [Changelog View](https://github.com/leits/MeetingBar/blob/master/MeetingBar/Views/Changelog/Changelog.swift)
  - [x] [CHANGELOG.md](https://github.com/leits/MeetingBar/blob/master/CHANGELOG.md)

### Steps to Test or Reproduce
- Open Preferences > Advanced
- Check the "Run AppleScript on keyboard shortcut" checkbox
- Choose a keyboard shortcut
- Hit "Edit script" and put in a script
- ???
- Profit!

### CODE REVIEW

**Comment by neilkimmett** [comment]
@leits anything else you need from me to help get this merged?

**Comment by leits** [comment]
Hi @neilkimmett. Sorry for the delay!
You can get the same result in a few clicks with the built-in macOS app Shortcuts. 
Thank you for the request and the implementation but sorry, but I'll close this PR to not inflate the application's functionality.

Share late if you managed to set up Shortcuts!

**Comment by leits** [comment]
Go to Shortcuts, click on "New command" button (+), and search "Run AppleScript" in actions. To assign a keyboard shortcut, open "Shortcut details" tab with (i) icon and use "Add keyboard shortcut" button.

The names of the buttons may be slightly different because I have Ukrainian localization :)

**Comment by neilkimmett** [comment]
Right, but what I want is to run an AppleScript _with the details of my next meeting_, which is where MeetingBar comes in.

**Comment by neilkimmett** [comment]
The use case I personally have is: when I press keyboard shortcut -> MeetingBar pulls out `meetingNotes` from my next meeting -> AppleScript parses and pulls out zoom meeting id and passcode from meeting notes, then puts them on screen (so I can dial into meeting from a conference room)

**Comment by leits** [comment]
I get you, @neilkimmett
Made a release with the actions of MeetingBar for Shortcuts. There is an action for getting the nearest event details so you can get event notes and pass them to AppleScript. Check it out!

**Comment by neilkimmett** [comment]
@leits oh nice yeah that should do the job for me. I just updated to 4.4 but for some reason MeetingBar's actions aren't showing up in the Shortcuts app. I'll see if I can figure out why, but if you have any pointers that would be fab. Thanks for all the hard work! 
image

**Pull request closed without merging**
