### PR TITLE
Add support for using the Chrome Canary browser

### PR DESCRIPTION
**Pull request by jeremywiebe**
### Status
**READY**

### Description
I have Chrome Canary installed, but not Chrome. This PR enables using Chrome Canary as a browser for various meetings. 

### Steps to Test or Reproduce
* Run MeetingBar
* Select **Google Chrome Canary** in the Services tab for one of the services
* Schedule a meeting on said service
* When meeting time arrives, select the meeting from MeetingBar to join it 
Note that you join with Chrome Canary (if installed)

### CODE REVIEW

**Comment by leits** [comment]
Thanks for the feature, @jeremywiebe!
I think it will be covered in https://github.com/leits/MeetingBar/pull/229.
@jgoldhammer working on robust browsers choosing.

**Comment by leits** [comment]
If for some reason #229 wouldn't be included in the next release, I'll merge this PR. So Canary support definitely be in the next release!

**Comment by jeremywiebe** [comment]
Thanks @leits . I'll leave this here.  Feel free to close it if you don't need it.

**Comment by jgoldhammer** [comment]
We have merged #229 , so I will close this MR! I hope this is ok @jeremywiebe

**Pull request closed without merging**
