### PR TITLE
Add localization manager

### PR DESCRIPTION
**Pull request by 2Grey**
### Status
**IN DEVELOPMENT**

### Description
- Added the ability to further localize the application;
- Added a russian localization;
- Added ui for change preferred language of application;
- Sort all MeetingServices by name in _ServicesTab_.

### Steps to Test or Reproduce
There is preferred language picker in General settings tab.
Localization key names are not the best.

### CODE REVIEW

**Comment by jgoldhammer** [comment]
Wow- thanks for the big merge request. We will have a look at it...

**Comment by jgoldhammer** [comment]
Hi @2Grey ,

sorry for being so late coming back.
 Can you merge your changes to resolve the conflicts? I will take a look then and I am willing to bring this into Meetingbar soon. @leits , ok?

**Comment by 2Grey** [comment]
@jgoldhammer, done.

**Comment by leits** [comment]
Thanks, @2Grey!

@jgoldhammer, ok!

**Comment by jgoldhammer** [comment]
Great work @2Grey ! Looks fine on a first look...

What do you think about this here? Should we translate that?
image


Keyboard Shortcuts does not support Russian at the moment. So we will still have "Record shortcut" as text.
https://github.com/sindresorhus/KeyboardShortcuts/tree/main/Sources/KeyboardShortcuts/Localization

What about this? Do we want to translate these options?

image

**Comment by 2Grey** [comment]
@jgoldhammer, 

**General tab**
1. Added localization for _Join meeting from clipboard_ (also fix typo in clipb**l**oar word).
2. Localized _Contact_ button text.
3. There is no need to translate _Patronage_ and _GitHub_ for Russian language.
But i added localied keys for it (if for some language these names will differ from the English).

**Bookmarks**
1. Add missed localized text for _Phone_ and _Other_.

**Comment by leits** [comment]
LGTM
@jgoldhammer, have all comments been resolved?

**Review by leits — APPROVED** [review]

**Comment by jgoldhammer** [comment]
LGTM!

**Pull request merged**
