### PR TITLE
Add support for pop meetings

### PR DESCRIPTION
**Pull request by Temikus**
### Status
READY

### Description
This adds support for https://pop.com/ remote pairing software that we heavily use.

## Checklist
- [x] Localized
- [x] Added to changelog:
  - [x] [Changelog View](https://github.com/leits/MeetingBar/blob/master/MeetingBar/Views/Changelog/Changelog.swift)
  - [x] [CHANGELOG.md](https://github.com/leits/MeetingBar/blob/master/CHANGELOG.md)

### Steps to Test or Reproduce
Simple unit test added but let me know if you need more.

### CODE REVIEW

**Comment by Temikus** [comment]
Re-pushed as I made a small mistake in tests.

**Review by jgoldhammer — APPROVED** [review]
LGTM!

**Comment by jgoldhammer** [comment]
I want to merge your pull request @Temikus - can you please fix the linting errors? Thx.

**Comment by jgoldhammer** [comment]
> I want to merge your pull request @Temikus - can you please fix the linting errors? Thx.

I have detected that we have a problem with swiftformat that times out with a specific rule. So I will try to fix this in master first and update this branch afterwards.

**Comment by jgoldhammer** [comment]
@Temikus  -additionally please add entries to the changelog files! Thx.

The swiftformat issue is fixed in #423, but needs to be merged into master.

**Comment by Temikus** [comment]
Oh man @jgoldhammer apologies, I think we collided a bit. Feel free to dismiss if my changes to changelog are not correct.

**Review by jgoldhammer — APPROVED** [review]

**Pull request merged**
